import {createClient} from '@supabase/supabase-js';import './admin.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const sb=(url&&key)?createClient(url,key):null;
let products=[];
document.querySelector('#admin').innerHTML=`<div class="login" id="login"><h1>CCshoppingmail</h1><h2>Private Admin</h2><input id="email" placeholder="Admin email" type="email"><input id="pass" placeholder="Password" type="password"><button id="signin">SIGN IN</button><p>Only accounts authorized by the Supabase Auth system can access this area.</p></div><div class="panel" id="panel" style="display:none"><header><h1>CCshoppingmail ADMIN</h1><button id="signout">Sign out</button></header><section><div class="bar"><h2>Products</h2><button id="new">+ New product</button></div><div id="list"></div></section><section><h2>Orders</h2><div id="orders"></div></section></div>`;
async function init(){if(!sb){document.querySelector('#login p').textContent='Add Supabase credentials in .env.local first.';return}const {data:{session}}=await sb.auth.getSession();if(session)show();sb.auth.onAuthStateChange((_e,s)=>s?show():hide())}
function hide(){login.style.display='block';panel.style.display='none'}function show(){login.style.display='none';panel.style.display='block';load()}
signin.onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:email.value,password:pass.value});if(error)alert(error.message)}
signout.onclick=()=>sb.auth.signOut();
document.querySelector('#new').onclick=()=>edit();
async function load(){const p=await sb.from('products').select('*').order('created_at',{ascending:false});products=p.data||[];list.innerHTML=products.map(x=>`<div class="row"><div><b>${x.name}</b><small>${x.category} · $${Number(x.price).toFixed(2)}</small></div><button onclick='window.edit(${JSON.stringify(x)})'>Edit</button><button onclick='window.del("${x.id}")'>Delete</button></div>`).join('');const o=await sb.from('orders').select('*').order('created_at',{ascending:false});orders.innerHTML=(o.data||[]).map(x=>`<div class="order"><b>${x.customer_email}</b> · $${Number(x.total).toFixed(2)} · ${x.status}<br><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p>No orders.</p>'}
window.edit=async(x={id:null,name:'',price:0,category:'Jewelry',description:'',image_url:'',active:true})=>{const name=prompt('Product name',x.name);if(name===null)return;const price=Number(prompt('Price',x.price));const cat=prompt('Category: Jewelry or Beauty',x.category);const desc=prompt('Description',x.description);const image=prompt('Image URL',x.image_url||'');const payload={name,price,category:cat,description:desc,image_url:image,active:true};let r=x.id?await sb.from('products').update(payload).eq('id',x.id):await sb.from('products').insert(payload);if(r.error)alert(r.error.message);else load()};
window.del=async(id)=>{if(confirm('Delete this product?')){const r=await sb.from('products').delete().eq('id',id);if(r.error)alert(r.error.message);else load()}};
init();
